Capstone project
alvaroiporre/Metal-Concert pull request #4
Opened 2023-04-19 21:27 UTC by alvaroiporre

### Rock and Roll Festival Project

- Topic that is different than the one in the original design. 
- I followed these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:
  * Colors. 
  * Typography
- Build only these 2 pages:
  * The home page.
  * The about page.
- Each of these pages have versions for 2 different screen sizes:
  * Mobile.
  * Desktop.
- Interaction:

  * The home page have a link to the about page in the menu.
  * The logo in the header links to the home page.
- Mobile Menu:
  * The mobile menu appears over the page when the user clicks (or taps) the hamburger button on the header.
  * The mobile menu should have a close (X) button that closes the menu.
- Dynamic Page:
  * The section "Artists" is created dynamically in JavaScript.
  * JavaScript variable with the content about the artists is created and is created dynamically when the page loads.
- Project Documentation:
  * A description of the project and add it to the readme file. 
  * A demo of the project features (different pages and different screen sizes). 

- Video description of the project [here]().

2023-04-20 00:51 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @alvaroiporre , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Indeed you did an exceptional but still, there is room for changes to complete this project. 💯


## Highlights 
☑️Well implemented design.
☑️Project is running live.
☑️Dynamic generated content.
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 00:51 UTC, ABDULALI3468 commented on js/main.js
> +    <h1 class="title fire">XXX EDITION</h1>
✅ Please consider using only one h1 tag throughout your page for semantic purposes as it helps the browser to better deal with the SEO and show the main content of the page.

## REMEMBER:-

This problem exists throughout the page so consider also replacing the other tags with some other suitable tag.

2023-04-20 00:51 UTC, ABDULALI3468 commented on js/main.js
> +<div class="main-content">
Please consider properly using the section tag. Currently, you are wrapping all the sections which are in this case div tags used by you rather than section tags.

## MORE ELABORATION:-

Kindly remove the section tag and replace all the div tags with the section tag to make your project one step closer to being semantically correct.

> Consider choosing a section tag or article tag according to what is suitable in which part of the page.


![image](https://user-images.githubusercontent.com/94223367/233227325-ca54953f-529e-43df-b597-29322e6bd16f.png)

2023-04-20 00:51 UTC, ABDULALI3468 commented on js/main.js
> +        <h1 class="title title-about fire">Rock & Roll 2023</h1>
Please consider properly using the section tag. Currently, you are wrapping all the sections which are in this case div tags used by you rather than section tags.

## MORE ELABORATION:-

Kindly remove the section tag and replace all the div tags with the section tag to make your project one step closer to being semantically correct.

> Consider choosing a section tag or article tag according to what is suitable in which part of the page.


![image](https://user-images.githubusercontent.com/94223367/233227701-1ef4ae34-877f-4f71-999e-9c19b49d1653.png)

2023-04-20 00:51 UTC, ABDULALI3468 commented on js/main.js
> +        <h1 class="title title-about fire">Rock & Roll 2023</h1>
Please consider not creating the **About page dynamically** as it's not asked in the project and is also not useful else consider creating it in an HTML file 💯 .

2023-04-20 00:51 UTC, ABDULALI3468 commented on js/main.js
> +<div class="main-content">
Please consider not creating the **Home page dynamically** as it's not asked in the project and is also not useful else consider creating it in an HTML file 💯 .

2023-04-20 00:51 UTC, ABDULALI3468 commented on js/main.js
> +        <h5 class="artist-subtitle">${artist.date}</h5>
Please consider wisely adding a proper subtitle rather than the plain date used in the page to meet the project requirements.

![image](https://user-images.githubusercontent.com/94223367/233228276-f2b166a4-876b-40ae-b34e-787ca014d0d6.png)

![image](https://user-images.githubusercontent.com/94223367/233228265-1f8b6a7a-7ff0-41f7-8e6b-cf4204f6e633.png)

2023-04-20 00:51 UTC, ABDULALI3468 commented on js/main.js
> +    <h2 class="main-location">Potosi - Bolivia</h2>
Please consider using the exact similar `font sizes, font weights, colors, and background-color` for them to make your project closer to the design.

![image](https://user-images.githubusercontent.com/94223367/233228376-ab341638-6a4f-4759-9205-f85f59c93678.png)

![image](https://user-images.githubusercontent.com/94223367/233228383-7153ce2c-1ad8-425f-9898-0c13cc167e77.png)

2023-04-20 00:51 UTC, ABDULALI3468 commented on js/main.js
> +            <p class="card-program-paragraph">No Alcoholic drinks are included along the festival.</p>
✅ Please consider adding a bit more, `font-weight` to all these paragraphs to make your project closer to the design.

2023-04-20 00:51 UTC, ABDULALI3468 commented on js/main.js
> +    <h2 class="sponsors-title">Sponsors</h2>
For the sponsors-title please consider using the same `color` to make your project closer to the design.

## ORIGINAL DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/233229025-f564fe79-9698-4743-8289-8cbedcbb0d9e.png)


## YOUR DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/233229067-b6c70309-8169-4167-a725-5c6a60c25321.png)

2023-04-20 00:51 UTC, ABDULALI3468 commented on index.html
> +        </div>
For the FOOTER TEXT please consider using the same `color` to make your project closer to the design.

## ORIGINAL DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/233229271-e2032ddf-1298-4d61-b32c-4f8efec2321d.png)


## YOUR DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/233229277-fd92481e-f90a-4a4d-97f6-cd92707bb128.png)

2023-04-20 12:24 UTC, alvaroiporre commented on js/main.js
> +        <h1 class="title title-about fire">Rock & Roll 2023</h1>
Thank you for your advice @ABDULALI3468 , but this is the best way that I found to change the page, I would not just hide a page while I show another one.

2023-04-20 12:25 UTC, alvaroiporre commented on js/main.js
> +<div class="main-content">
Thank you for your advice @ABDULALI3468 , but this is the best way that I found to change the page, I would not just hide a page while I show another one.

2023-04-20 12:52 UTC, alvaroiporre commented
I made the required changes!

2023-04-20 14:09 UTC, DuaneDave requested changes
Hi @alvaroiporre 👋, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-20 14:09 UTC, DuaneDave commented on js/main.js
> +        </div>
As the previous reviewer pointed out, there should exist only one `h1` tag throughout a page. One exits already at the hero section of the about page and we have two more here. Consider having just one to make the webpage easy to rank in SEO.

2023-04-20 14:09 UTC, DuaneDave commented on index.html
> +        </div>
As previously asked by the previous reviewer, please ensure to stick as much as possible with the provided color scheme so your design matches the template. From eyeballing the color, i think the color for this text is same as the one used for the sponsor or maybe something lighter. Play with the color until you get it right

2023-04-20 14:09 UTC, DuaneDave commented on js/main.js
> +    <h2 class="sponsors-title">Sponsors</h2>
[OPTIONAL] You are obviously using the correct color for the text, but the background color of the container makes it appear differently. You can consider updating the color to make your design math that of the template.

2023-04-20 14:09 UTC, DuaneDave commented on js/main.js
> +    <p class="paragraph-main">“We have realized that our weapons to make the world a little better are music and the festival. This is what We know how to do well.”</p>
As previously asked, please do not create both the about and home page dynamically apart from the artist section. Currently the goal for you is to learn how to link between html file. So in a bid to solve this, consider creating another html file for the about page and paste the markup for the about there.

After that let the link for the about page on the navbar link to about.html, using this approach will make the load time faster and make you stick with the requirements

like this:

```
<a href='about.html`>about</a>
```

You can do same for the homepage.

2023-04-20 15:30 UTC, alvaroiporre commented on js/main.js
> +    <p class="paragraph-main">“We have realized that our weapons to make the world a little better are music and the festival. This is what We know how to do well.”</p>
Thank you for the pieces of advice @DuaneDave. Very good code review.

2023-04-20 15:31 UTC, alvaroiporre commented
Fix Changes required by @DuaneDave.

2023-04-20 17:49 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @alvaroiporre ,
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
 :heavy_check_mark: Linters are passing.
:heavy_check_mark: You have a good code structure.
 
 ## Required Changes 

_Check Under the Review
 
 ## Optional suggestions 

- [ ] As required for this project You should  create a professional 5-minute video showcasing the project's features, providing a clear and concise description in professional English, demonstrating the project's pages in different screen sizes, and highlighting a piece of code they found interesting or are proud of making. :wink:  KIndly record a video , add it in the `readme file`

- [ ] Check Under the review

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 17:49 UTC, Alfredbis29 commented on js/main.js
> +      <img class="artist-image" src="${artist.image}" alt="${artist.name}">
- [ ] As required in the previous [Review](https://github.com/alvaroiporre/Metal-Concert/pull/4#discussion_r1171970990), you should consider matching your design to the template one, I just noticed that you are missing this part of the design on your project kindly add it for your design to match the template design, fix this please :point_down: 
![Screenshot from 2023-04-20 19-30-56](https://user-images.githubusercontent.com/88894525/233444294-445df237-6518-4386-9952-5064fb165df6.png)

2023-04-20 17:49 UTC, Alfredbis29 commented on index.html
> +            <h4>2023 - Some Rights Reserved.</h4>
- [ ] As requested by the previous [reviewer](https://github.com/alvaroiporre/Metal-Concert/pull/4#discussion_r1171974419) consider use the same font and colors for your footer to match the design 

![Screenshot from 2023-04-20 19-42-20](https://user-images.githubusercontent.com/88894525/233445954-16789b32-f122-4a6b-bca3-b7466e1539cf.png)

2023-04-20 17:49 UTC, Alfredbis29 commented on about.html
> +                Perhaps most importantly, this festival creator is passionate about giving back to the community. They understand the power of music to bring people together and to create positive ch
- [Optional] KIndly style this paragraph since it contains important informations for your event, I can see that is not really readable :wink: 
![Screenshot from 2023-04-20 19-44-28](https://user-images.githubusercontent.com/88894525/233446590-0b8f9478-203d-499a-bda7-8f08b5f25425.png)

2023-04-20 18:01 UTC, alvaroiporre commented on js/main.js
> +      <img class="artist-image" src="${artist.image}" alt="${artist.name}">
@Alfredbis29 please be clear, I don't understand what exactly I need to add.

2023-04-20 18:02 UTC, alvaroiporre commented on index.html
> +            <h4>2023 - Some Rights Reserved.</h4>
@Alfredbis29 I'm using the same fon and color. I don't know what you mean.

2023-04-20 18:07 UTC, Alfredbis29 commented on js/main.js
> +      <img class="artist-image" src="${artist.image}" alt="${artist.name}">
Hello @alvaroiporre , thanks for the quick feedback , so I can see that you missed that part on your design , and as  required in the previous review , instead of using :point_down:  you should follow the design guidelines . I think that make sense if any further  question or you need some help reach me out :wink: 
![Screenshot from 2023-04-20 20-04-03](https://user-images.githubusercontent.com/88894525/233450840-e58a575e-bd3a-40df-b587-1be3f89187aa.png)

2023-04-20 18:11 UTC, alvaroiporre commented on js/main.js
> +      <img class="artist-image" src="${artist.image}" alt="${artist.name}">
@Alfredbis29 I still don't understand what you mean whit "that part".

2023-04-20 18:23 UTC, Alfredbis29 commented on index.html
> +            <h4>2023 - Some Rights Reserved.</h4>
@alvaroiporre  refer yourself to the previous reviews you will get everything I mean please

2023-04-21 07:56 UTC, Nemwel-Boniface reviewed
## Hello @alvaroiporre   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request complaining about the previous reviewer's (@Alfredbis29 ) comments which are not clear. Below are my findings:

- [ ] For this [requested change,](https://github.com/alvaroiporre/Metal-Concert/pull/4#discussion_r1172904651) it is clear that the reviewer was not consistent with his previous reviewer (@DuaneDave ) and ended up requesting changes that were requested by the first reviewer (@ABDULALI3468 ). In this specific case, he (@Alfredbis29 ) ought to have request this change as an [OPTIONAL] since @DuaneDave did not point it out. It is also note very clear what exactly needs changes as it was not contrasted side by side with the original design.
- [ ] For this [requested change](https://github.com/alvaroiporre/Metal-Concert/pull/4#discussion_r1172907654), while it was already mentioned by both reviewers, what @Alfredbis29 ought to have done is to clarify that the section that does not match the typography is the background color of the footer which is different from the one that is in the [Behance design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). To get the color used, you can use an extension that is called [ColorPick Eyedropper](https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg?hl=en). However, in my opinion, this could have been overlooked.

**Side note:** I however think that you having gone the extra mile to render the about page dynamically was a great thing which ought to have been commended :clap: . The main aim of this project is to learn and apply the concepts that you learn :slightly_smiling_face: 


In my opinion, your project should have been approved and any other change should have been requested as [OPTIONAL[ because of consistency matters.

As this was the only reason that your project was not approved it will be approved as soon as possible.

Please note that since we will approve it manually so this could take a few hours!

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

2023-04-21 10:55 UTC, alvaroiporre commented
Thanks you so much @Nemwel-Boniface.

2023-04-21 10:56 UTC, merged

2023-04-21 11:19 UTC, NahnahAJ commented
## Project Status: APPROVED :green_circle: 
Hi @alvaroiporre , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights
- Your Project looks great :heavy_check_mark: 
- Professional README :heavy_check_mark: 
- All requested changes implemented :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._